name: CICD

on:
  schedule:
    - cron: '*/10 * * * *'

env:
  DOCKER_BUILDKIT: 1 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release-name: ["mainnet", "testnet"]
    steps:
      - uses: actions/checkout@v2
      - name: Get Github Tag
        env: 
          RELEASE_NAME: ${{ matrix.release-name }}
        run: |
          regex=""
          if [ "$RELEASE_NAME" == "mainnet" ]; then 
            regex="[0-9]+.[0-9]+.[0-9]+$"
          elif [ "$RELEASE_NAME" == "testnet" ]; then
            regex="[0-9]+.[0-9]+.[0-9]+-rc+"
          elif [ "$RELEASE_NAME" == "betanet" ]; then
            regex="[0-9]+.[0-9]+.[0-9]+-beta+" 
          fi
          echo $(curl -s https://api.github.com/repos/nearprotocol/nearcore/releases | jq -c -r --arg regex "$regex" 'map(select(.tag_name | test($regex)))[0].tag_name') > github-tag.txt

      - name: Install Rust
        if: ${{ success() }}
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly-2020-03-19

      - name: Clone NEARCore
        if: ${{ success() }}
        uses: actions/checkout@v2
        with:
          repository: nearprotocol/nearcore
          ref: ${{ env.RELEASE_VERSION }}

      - name: Cargo Test
        run: cargo test
            
      - name: Test neard
        run: cd neard && cargo test    
